# Generated by Django 5.0.1 on 2024-02-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente_name', models.CharField(max_length=60, verbose_name='Nombre del cliente')),
                ('Cedula', models.CharField(max_length=13, verbose_name='numero de cedula o Ruc')),
                ('Ciudad', models.CharField(max_length=60, verbose_name='Ciudad')),
                ('Sector', models.CharField(max_length=60, verbose_name='Sector')),
                ('Referencia', models.CharField(max_length=60, verbose_name='Referencia')),
                ('Calle_principal', models.CharField(max_length=60, verbose_name='Calle principal')),
                ('Calle_secundaria', models.CharField(max_length=60, verbose_name='Calle secundaria')),
                ('Numero_de_domicilio', models.CharField(max_length=60, verbose_name='Numero de domicilio')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('6', '6'), ('7', '7'), ('12', '12')], max_length=2, verbose_name='Numero de serie')),
                ('Number_order', models.CharField(max_length=30, verbose_name='Numero de pedido')),
                ('Items_pedido', models.CharField(max_length=30, verbose_name='Numero de items en el pedido')),
                ('date_expired_delivery', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('Envio_cliente', models.BooleanField(default=False)),
                ('Acondicionamiento', models.BooleanField(default=False)),
                ('Tipo_acondi', models.CharField(blank=True, choices=[('Armados de Kits', 'Armados de Kits'), ('Acond. AVANOS ', 'Acond. AVANOS'), ('Acond. Impresión', 'Acond. Impresión'), ('Acond. Meditec ', 'Acond. Meditec ')], max_length=30, verbose_name='Tipo de acondicionamiento')),
                ('Cantidad_acond', models.CharField(blank=True, max_length=30, verbose_name='cantidad unidades acondicionamiento')),
                ('Cantidad_personas', models.CharField(blank=True, max_length=2, verbose_name='cantidad personas ingresan a acondi')),
                ('Status_prepara', models.BooleanField(default=False)),
                ('Respnsable_prep', models.CharField(blank=True, choices=[('Rafael', 'Rafael'), ('Esteban', 'Esteban'), ('Randy', 'Randy'), ('Marco', 'Marco'), ('Guillermo', 'Guillermo'), ('Orlando', 'Orlando'), ('Edwin', 'Edwin'), ('Lorena', 'Lorena'), ('Otro', 'Otro')], max_length=30, verbose_name='Responsable prepa')),
                ('Status_Revisado', models.BooleanField(default=False)),
                ('Respnsable_revi', models.CharField(blank=True, choices=[('Rafael', 'Rafael'), ('Esteban', 'Esteban'), ('Randy', 'Randy'), ('Marco', 'Marco'), ('Guillermo', 'Guillermo'), ('Orlando', 'Orlando'), ('Edwin', 'Edwin'), ('Lorena', 'Lorena'), ('Otro', 'Otro')], max_length=30, verbose_name='Responsable revi')),
                ('Guias', models.CharField(blank=True, max_length=15, verbose_name='Numero de Guia')),
                ('Cajas', models.CharField(blank=True, max_length=30, verbose_name='Numero de bultos')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('Cerrado', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.cliente')),
            ],
        ),
    ]
