# Generated by Django 5.0.1 on 2024-02-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Items_pedido',
            field=models.IntegerField(verbose_name='Numero de items en el pedido'),
        ),
    ]
