# Generated by Django 5.0.1 on 2024-02-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_pedido_items_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Detalle_novedad',
            field=models.CharField(blank=True, max_length=100, verbose_name='cantidad personas ingresan a acondi'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='novedad_pedido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cantidad_acond',
            field=models.IntegerField(verbose_name='cantidad unidades acondicionamiento'),
        ),
    ]
