# Generated by Django 5.0.1 on 2024-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Correo elactronico')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='Numero de cedula')),
                ('active_user', models.BooleanField(default=True)),
                ('admin_user', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de telefono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pefil')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
